export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD'

export const FETCH_KITTIES_PENDING = 'FETCH_KITTIES_PENDING'
export const FETCH_KITTIES_SUCCESS = 'FETCH_KITTIES_SUCCESS'
export const FETCH_KITTIES_fAILED = 'FETCH_KITTIES_fAILED'
